 //O volume na unidade Z ‚ eco
 //O N£mero de S‚rie do Volume ‚ 4A91-94E4

 //Pasta de Z:\ca2\app\axis\crypto\crypto\des

#include "cbc3_enc.c"
#include "cbc_cksm.c"
#include "cbc_enc.c"
#include "cfb64ede.c"
#include "cfb64enc.c"
#include "cfb_enc.c"
//#include "des.c"
//#include "destest.c"
#include "des_enc.c"
//#include "des_old.c"
//#include "des_old2.c"
//#include "des_opts.c"
#include "ecb3_enc.c"
#include "ecb_enc.c"
#include "ede_cbcm_enc.c"
#include "enc_read.c"
#include "enc_writ.c"
#include "fcrypt.c"
#include "fcrypt_b.c"
//#include "ncbc_enc.c"
#include "ofb64ede.c"
#include "ofb64enc.c"
#include "ofb_enc.c"
#include "pcbc_enc.c"
#include "qud_cksm.c"
#include "rand_key.c"
#include "read2pwd.c"
//#include "read_pwd.c"
#include "rpc_enc.c"
//#include "rpw.c"
#include "set_key.c"
//#include "speed.c"
#include "str2key.c"
#include "xcbc_enc.c"
//#include "_des.c"
//              35 arquivo(s)        260.415 bytes
//               0 pasta(s)   29.040.791.552 bytes dispon¡veis
