#ifndef FREERDP_BUILD_CONFIG_H
#define FREERDP_BUILD_CONFIG_H

#ifdef _WIN32

#define FREERDP_VENDOR_STRING "ca2"


#define FREERDP_PRODUCT_STRING "rdpclient"



#define FREERDP_DATA_PATH "%APPDATA%/ca2/system/FreeRDP"
#define FREERDP_KEYMAP_PATH ""
#define FREERDP_PLUGIN_PATH "lib/freerdp"

#define FREERDP_INSTALL_PREFIX "C:/Program Files (x86)/FreeRDP"

#define FREERDP_LIBRARY_PATH "lib"

#define FREERDP_ADDIN_PATH "lib/freerdp"

#define FREERDP_SHARED_LIBRARY_PREFIX ""

//#define FREERDP_DATA_PATH "${FREERDP_DATA_PATH}"
//#define FREERDP_KEYMAP_PATH "${FREERDP_KEYMAP_PATH}"
//#define FREERDP_PLUGIN_PATH "${FREERDP_PLUGIN_PATH}"
//
//#define FREERDP_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
//
//#define FREERDP_LIBRARY_PATH "${FREERDP_LIBRARY_PATH}"
//
//#define FREERDP_ADDIN_PATH "${FREERDP_ADDIN_PATH}"
//
//#define FREERDP_SHARED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}"
//#define FREERDP_SHARED_LIBRARY_PREFIX  "${CMAKE_SHARED_LIBRARY_PREFIX}"
//
//#define FREERDP_VENDOR_STRING "${VENDOR}"
//#define FREERDP_PRODUCT_STRING "${PRODUCT}"

#else

#define FREERDP_VENDOR_STRING "ca2"


#define FREERDP_PRODUCT_STRING "rdpclient"



#define FREERDP_DATA_PATH "C:/Program Files (x86)/FreeRDP/share/freerdp"
#define FREERDP_KEYMAP_PATH ""
#define FREERDP_PLUGIN_PATH "lib/freerdp"

#define FREERDP_INSTALL_PREFIX "C:/Program Files (x86)/FreeRDP"

#define FREERDP_LIBRARY_PATH "lib"

#define FREERDP_ADDIN_PATH "lib/freerdp"

#endif

#endif /* FREERDP_BUILD_CONFIG_H */
