//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vmplight.rc
//
#define IDAPPLY                         3
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_OPTIONS_IMAGES_DIRECTORIES  101
#define IDS_MIXER_PLAYBACK_TAB          101
#define IDS_MIXER_RECORDING_TAB         102
#define IDS_OPTIONSVIEW_TAB_FOLDERS     103
#define IDS_MIXER_MUTEALL               104
#define IDS_MIXER_MUTE                  105
#define IDR_MAINFRAME                   128
#define IDR_VMPLIGTYPE                  129
#define IDR_MAINFRAME1                  129
#define IDR_POPUP_LYRICVIEW             129
#define IDD_OPTIONS                     130
#define IDI_FULLSCREEN                  130
#define IDR_POPUP_LYRICVIEW_LINK        130
#define IDI_VIEW_FULLSCREEN             130
#define IDR_PLAYLIST                    131
#define IDR_ALBUM                       132
#define IDI_EXECUTE_PAUSE               133
#define IDR_FILEMANAGER_OPENMUSIC       133
#define IDI_EXECUTE_MINUS_ONE           134
#define IDR_POPUP_PLAYLIST              134
#define IDD_OPTIONS_SONGS_DIRECTORIES   135
#define IDI_APP_EXIT                    135
#define IDR_POPUP_PLAYLIST_ITEM         135
#define IDI_FILE_OPEN                   136
#define IDR_POPUP_FILEOPEN_ITEM         136
#define IDI_FILE_OPEN_EX                136
#define IDD_OPTIONS_IMAGES              137
#define IDR_MUSICALPLAYER               137
#define IDR_POPUP_FILEOPEN              137
#define IDR_POPUP_ALBUM_ITEM            138
#define IDR_POPUP_ALBUM                 139
#define IDR_MAINFRAME2                  140
#define IDR_MAINFRAME_INLINE            141
#define IDR_POPUP_FILEOPEN_DIRECTORY    142
#define IDR_POPUP_LYRICVIEW1            143
#define IDR_POPUP_LYRICVIEW_COMPLETE    143
#define IDI_VIEW_ALBUM                  144
#define IDI_VIEW_PLAYLIST               145
#define IDD_ERROR                       147
#define IDC_HAND_POINTER                147
#define IDR_VIEW                        148
#define IDR_ALBUM_DIALOGBAR             150
#define IDD_WAIT_MESSAGE                151
#define IDI_ICON1                       152
#define IDB_BITMAP_ABOUT                155
#define IDD_OPTIONS_AUDIO_DEVICES       156
#define IDR_MEDIALIBRARY                156
#define IDI_LANGUAGE_CHANGE             158
#define IDR_OPTIONSFRAME                160
#define IDI_KARAOKE_BOUNCING_BALL       162
#define IDI_KARAOKE_GRADUAL_FILLING     163
#define IDR_PNG_VMPLITE_ABOUT           164
#define IDI_VMSKARLIB_FOLDER_NORMAL     165
#define IDI_VMSKARLIB_ARTIST_NORMAL     166
#define IDI_CONTEXT_MENU                167
#define IDD_OPTIONS_GENERAL             190
#define IDI_BB2                         198
#define IDI_FILEMANAGER_EXPANDBOX       199
#define IDD_FILE_ASSOCIATIONS           217
#define IDR_FILEMANAGER_DIALOGBAR       218
#define IDI_BB1                         259
#define IDI_BB1_PRESSED1                261
#define IDI_BB2_PRESSED1                262
#define IDI_FILE_ADD                    263
#define IDI_EDIT_REMOVE                 264
#define IDI_EXECUTE_PLAY                265
#define IDI_EXECUTE_STOP                266
#define IDI_VIEW_KARAOKE                267
#define IDI_FILEMANAGER_COLLAPSEBOX     268
#define IDI_SOUND_RECORDING             269
#define IDI_MIDI_PLAYBACK               270
#define IDI_VMSKARLIB_FOLDER_SELECTED   271
#define IDI_VMSKARLIB_ARTIST_SELECTED   272
#define IDI_VMSKARLIB_SONG_NORMAL       273
#define IDI_MIXER_PLAYBACK              274
#define IDI_MIXER_RECORDING             275
#define IDI_EXECUTE_RECORD              276
#define IDC_TAB                         1000
#define IDC_ADD                         1001
#define IDC_REMOVE                      1002
#define IDC_LIST                        1004
#define IDC_EDIT_SYNCH_DELAY            1007
#define IDC_EDIT_CHANGE_TIME            1008
#define IDC_EDIT_MESSAGE                1008
#define IDC_SPIN_CHANGE_TIME            1009
#define ID_CONTINUE                     1009
#define ID_CANCEL                       1010
#define IDC_RADIO_SEQUENTIAL            1011
#define IDC_EDIT_TIMEOUT                1011
#define IDC_RADIO_RANDOM                1012
#define IDC_STATIC_TITLE                1013
#define IDC_STATIC_SYNCH_DELAY          1015
#define IDC_STATIC_ICON                 1016
#define IDC_STATIC_COPYRIGHT            1017
#define IDC_STATIC_SEARCH               1018
#define IDC_STATIC_MIDI_PLAYBACK_LABEL  1019
#define IDC_STATIC_AUDIO_RECORDING_LABEL 1020
#define IDC_STATIC_MIDI_PLAYBACK_ICON   1022
#define IDC_STATIC_AUDIO_RECORDING_ICON 1023
#define IDC_STATIC_AUDIO_RECORDING      1025
#define IDC_STATIC_MIDI_PLAYBACK        1026
#define IDC_STATIC_IMAGE                1049
#define IDC_STATIC_TEXT                 1050
#define IDC_BUTTON1                     1051
#define IDC_EDIT_ADVANCED               1052
#define IDC_COMBO_SOUND_RECORDING       1312
#define IDC_COMBO_MIDI_PLAYBACK         1313
#define IDC_CHECK_MRU                   1400
#define IDC_SPIN_MRU                    1401
#define IDC_EDIT_MRU_COUNT              1402
#define IDC_CHECK_MID                   1410
#define IDC_CHECK_KAR                   1411
#define IDC_CHECK_ST3                   1412
#define IDC_ST_FILE_EXTENSION           1415
#define IDC_EDIT_SEARCH                 6000
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_EXECUTE_PLAY                 32771
#define ID_KARAOKE_BOUNCING_BALL        32773
#define ID_KARAOKE_GRADUAL_FILLING      32774
#define ID_TOOLS_OPTIONS                32775
#define ID_EXECUTE_STOP                 32777
#define ID_EXECUTE_PAUSE                32779
#define ID_EXECUTE_MINUSONE             32780
#define ID_EXECUTE_MINUS_ONE            32781
#define ID_VIEW_PLAYLIST                32782
#define ID_VIEW_FULLSCREEN              32783
#define ID_EDIT_REMOVEDELETE            32790
#define ID_EDIT_REMOVE                  32791
#define ID_VIEW_ALBUM                   32795
#define ID_FILE_ADD                     32796
#define ID_VIEW_ENCODING_LATIN1         32797
#define ID_VIEW_ENCODING_SHIFTJIS       32798
#define ID_COPY_LINK_LOCATION           32799
#define ID_FILE_                        32800
#define ID_BROWSE_LEVELUP               32801
#define ID_VIEW_KARAOKE                 32804
#define ID_FILE_OPEN_EX                 32807
#define ID_VIEW_MEDIAEXPLORER           32809
#define ID_VIEW_ALLMEDIA                32810
#define ID_TOGGLECUSTOMFRAME            32813
#define ID_PLAYLIST_EXECUTE_PLAY        32814
#define ID_VIEW_OPTIONS                 32816
#define ID_EDIT_ADD                     32817
#define ID_VIEW_NEXT_PANE               32821
#define ID_ALBUM_PLAYLIST_EXECUTE_PLAY  32825
#define ID_ALBUM_EXECUTE_PLAY           -32710
#define ID_EXECUTE_NEXT                 32827
#define ID_EXECUTE_PREVIOUS             32828
#define ID_FILE_MRU_FILE                32829
#define ID_VIEW_VERIWELLKARAOKELIBRARYEXPLORER 32830
#define ID_OPEN_LINK_IN_NEW_WINDOW      32984
#define ID_ADDTOMEDIALIBRARY            32985
#define ID_EXECUTE_ADDTOPLAYLIST        32986
#define ID_SUBST_SO_SHELL_MENU          32987
#define ID_PLAY_AUTORECORD              32988
#define ID_EXECUTE_AUTO_RECORD          32989
#define ID_VMSGUI_CLOSE                 33333
#define ID_VMSGUI_WINDOW_UP             33334
#define ID_VMSGUI_WINDOW_DOWN           33335
#define ID_VMSGUI_WINDOW_MINIMIZE       33336
#define ID_VMSGUI_WINDOW_MAXIMIZE       33337
#define ID_VMSGUI_WINDOW_RESTORE        33338
#define ID_VMSGUI_NOTIFY_ICON           33339
#define IDS_CHOOSE_IMAGE_DIRECTORY      34467
#define IDS_NO_DIRECTORY_SELECTED       34468
#define IDS_OPTIONS_FILE_ASSOCIATIONS   34469
#define IDS_MIDIMAPPER                  34536
#define IDS_OPTIONS_AUDIODEVICES        34537
#define IDS_WAVEMAPPER                  34538
#define IDS_KARAOKEVIEW_TAB_KARAOKE     34539
#define IDS_KARAOKEVIEW_TAB_PLAYLIST    34540
#define IDS_KARAOKEVIEW_TAB_ALBUM       34541
#define IDS_KARAOKEVIEW_TAB_OPEN        34542
#define IDS_KARAOKEVIEW_TAB_OPTIONS     34543
#define IDS_KARAOKEVIEW_TAB_AUDIOCONTROL 34544
#define IDS_OPTIONS_GENERAL             34591
#define IDS_OPTIONS_SONGSFOLDER         34600
#define IDS_OPTIONS_IMAGESFOLDERS       34601
#define IDS_OPTIONS_IMAGES              34602
#define IDS_XFPLAYER_OPENFILETITLE      34603
#define IDS_XFPLAYER_OPENFILEFILTER     34604
#define IDS_XFPLAYER_OPENFILEFILTER2    34605
#define IDS_OPTIONSFOLDERS_TAB_SONG     35000
#define IDS_OPTIONSFOLDERS_TAB_IMAGE    35001
#define IDS_OPTIONSFOLDERS_TAB_AUTO_RECORD 35002
#define IDS_MID                         63000
#define IDS_KAR                         63001
#define IDS_ST3                         63002
#define ID_LANGUAGE_CHANGE              60000
#define ID_LANGUAGE_CHANGE1             60001
#define ID_LANGUAGE_CHANGE2             60002
#define ID_LANGUAGE_CHANGE3             60003
#define ID_LANGUAGE_CHANGE4             60004
#define ID_LANGUAGE_CHANGE5             60005
#define ID_LANGUAGE_CHANGE6             60006
#define ID_LANGUAGE_CHANGE7             60007
#define ID_LANGUAGE_CHANGE8             60008
#define ID_LANGUAGE_CHANGE9             60009
#define ID_LANGUAGE_CHANGE10            60010
#define ID_LANGUAGE_CHANGE11            60011
#define ID_LANGUAGE_CHANGE12            60012
#define ID_VIEW_ENCODING                60100
#define ID_VIEW_ENCODING_1              60101
#define ID_VIEW_ENCODING_2              60102
#define ID_VIEW_ENCODING_3              60103
#define ID_VIEW_ENCODING_4              60104
#define ID_VIEW_ENCODING_5              60105
#define ID_VIEW_ENCODING_6              60106
#define ID_VIEW_ENCODING_7              60107
#define ID_VIEW_ENCODING_8              60108
#define ID_VIEW_ENCODING_9              60109
#define ID_VIEW_ENCODING_10             60110
#define ID_VIEW_ENCODING_11             60111
#define ID_VIEW_ENCODING_12             60112
#define IDS_FILE_OPEN_ERROR             62002
#define IDS_PLAYLIST_HEADER_FILENAME    61447
#define IDS_PLAYLIST_HEADER_FILEPATH    61448
#define IDS_APP_OPTIONS_GENERAL_SYNCH_DELAY 61449
#define IDS_VIEW_LANGUAGE               61450
#define IDS_OPTIONSVIEW_TAB_SONGDIRECTORIES 61451
#define IDS_OPTIONSVIEW_TAB_IMAGEDIRECTORIES 61452
#define IDS_VIEW_ENCODING_LATIN1        61453
#define IDS_VIEW_ENCODING_SHIFTJIS      61454
#define IDS_VIEW_ENCODING_BIG5          61455
#define IDS_OPTIONSVIEW_TAB_FILEASSOCIATION 61456
#define IDS_OPTIONSVIEW_TAB_AUDIODEVICES 62000
#define IDS_MEDIALIBRARY_TAB_ALL        61458
#define IDS_MEDIALIBRARY_TAB_EXPLORER   61459
#define IDS_MEDIALIBRARY_TAB_VMSKARLIB  61460
#define IDS_VIEW_ENCODING_SHIFTEUCJP    61461
#define IDS_VIEW_ENCODING_ISO2022JP     61462
#define IDS_VIEW_ENCODING_MACJP         61463
#define IDS_VIEW_ENCODING_AUTODETECT    61464
#define IDS_OPTIONSVIEW_TAB_KARAOKE     61465
#define IDS_KARAOKEVIEW_TAB_MENU        62001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32990
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
