#!/bin/bash
#

FTP_HOST="208.109.188.16"
FTP_USER="gustavo"
FTP_PASSWORD="h1p.t5mLJpC3r"


function dbbk()
{
	DATABASE=$1
	
	dbclean $DATABASE

	DATE=`date +%Y-%m-%d`

	mysqldump -u root -ph1p.t5mLJpC3r $1 > /votagus/time/ca2/fontopus/sys/bk/database-$DATABASE-$DATE.sql
	gzip /votagus/time/ca2/fontopus/sys/bk/database-$DATABASE-$DATE.sql

	ftp_put database-$DATABASE-$DATE.sql.gz

	# rm -rf /votagus/time/ca2/fontopus/sys/bk/database-$DATABASE-$DATE.sql.gz
}


function dirbk()
{
TOPIC=$1
DIRECTORIES=$2

dirclean $TOPIC

DATE=`date +%Y-%m-%d`

# Dados do arquivo de backup
FILE="backup-$TOPIC-$DATE.tar.gz"


# A partir daqui não precisa mais editar.
# Cria o arquivo .tar.gz no /votagus/time/ca2/fontopus/sys/bk (Temporário)
cd /votagus/time/ca2/fontopus/sys/bk
tar zcf /votagus/time/ca2/fontopus/sys/bk/$FILE $DIRECTORIES


ftp_put $FILE

# Remove os arquivos temporarios
# rm -rf /votagus/time/ca2/fontopus/sys/bk/$FILE
}


function ftp_put()
{
FILE=$1

# Acessa o FTP e coloca os arquivos
ftp -in <<FTP_PUT
   open $FTP_HOST
   user $FTP_USER $FTP_PASSWORD
   bin
   lcd /votagus/time/ca2/fontopus/sys/bk
   dele $FILE
   put $FILE
   bye
FTP_PUT
}

function dirclean()
{
TOPIC=$1

DATE=`date -d "3 day ago" +%Y-%m-%d`

# Dados do arquivo de backup
FILE="backup-$TOPIC-$DATE.tar.gz"

# Acessa o FTP e coloca os arquivos
ftp -in <<FTP_DIR_CLEAN
   open $FTP_HOST
   user $FTP_USER $FTP_PASSWORD
   bin
   dele $FILE
   bye
FTP_DIR_CLEAN
}

function dbclean()
{
DATABASE=$1

DATE=`date -d "3 day ago" +%Y-%m-%d`

# Dados do arquivo de backup
FILE="database-$DATABASE-$DATE.sql.gz"

# Acessa o FTP e coloca os arquivos
ftp -in <<FTP_DIR_CLEAN
   open $FTP_HOST
   user $FTP_USER $FTP_PASSWORD
   bin
   dele $FILE
   bye
FTP_DIR_CLEAN
}

function copy_mask()
{
	local file;
	for file in $1/*
	do
		if [ -d "$file" ]
		then
			#echo "Directory:"
			#echo "$file"
			copy_mask "$file" "$2"
		fi
	done
	for file in $1/cfg
	do
		if [ -f "$file" ]
		then
			echo "$file"
			mkdir -p "$2$1"
			cp "$file" "$2$file"
		fi
	done
}


function home_bk_setup()
{
	mkdir -p /home/bk/setup
	copy_mask "/home/setup" "/home/bk/setup"
}




dbbk "ccvotagus"
dbbk "cyncecc"
dbbk "fontopus"
dbbk "gustavocc"
dbbk "information_schema"
dbbk "mysql"
dbbk "phpmyadmin"
dirbk "votagus_ccvotagus" "/home/repos/ccvotagus"
dirbk "votagus_seed" "/home/repos/seed"
dirbk "votagus_appseed" "/home/repos/appseed"
dirbk "votagus_netseed" "/home/repos/netseed"
dirbk "votagus_matter" "/home/repos/matter"
dirbk "votagus_appmatter" "/home/repos/appmatter"
dirbk "votagus_netmatter" "/home/repos/netmatter"
dirbk "votagus_node" "/home/repos/node"
dirbk "votagus_stage" "/home/repos/stage"
dirbk "etc" "/etc"
home_bk_setup
dirbk "home_bk_setup" "/home/bk/setup"
