#!/bin/bash
#

DATE=`date +%Y-%m-%d`

mysqldump -u root -ph1p.t5mLJpC3r $1 > /tmp/database-$1-$DATE.sql
gzip /tmp/database-$1-$DATE.sql

$SCRIPT_BASE/ftp_put database-$1-$DATE.sql.gz

rm -rf /tmp/database-$1-$DATE.sql.gz




