#!/bin/bash
#

TOPIC=$1

$SCRIPT_BASE/ftp_def

DATE=`date -d "3 day ago" +%Y-%m-%d`

./ftp_def

# Dados do arquivo de backup
TOPIC=$1
FILE="backup-$TOPIC-$DATE.tar.gz"

# Acessa o FTP e coloca os arquivos
ftp -in <<EOF
   open $FTP_HOST
   user $FTP_USER $FTP_PASSWORD
   bin
   dele $FILE
   bye
EOF
