#!/bin/bash
#

TOPIC=$1

DATE=`date -d "3 day ago" +%Y-%m-%d`

# Acessa o FTP e coloca os arquivos
ftp -in <<EOF
   open $FTP_HOST
   user $FTP_USER $FTP_PASSWORD
   bin
   dele $FILE
   put $FILE
   bye
EOF


