#!/bin/bash
#

$SCRIPT_BASE/ftp_def

# Acessa o FTP e coloca os arquivos
ftp -in <<EOF
   open $FTP_HOST
   user $FTP_USER $FTP_PASSWORD
   bin
   lcd /tmp
   dele $FILE
   put $FILE
   bye
EOF
