#pragma once


#include "app/appseed/axis/axis/axis/axis.h"

#include <half.h>

#include "IlmThreadPool.h"
#include "IlmThreadSemaphore.h"
#include "IlmThreadMutex.h"

#include "ImathBox.h"
#include "ImathFun.h"
#include "ImathVec.h"

#include "Iex.h"

//#include <algorithm>
//#include <cmath>
//#include <fstream>
//#include <iostream>
//#include <iomanip>
//#include <map>
//#include <sstream>
//#include <string>
//#include <vector>

#include <assert.h>
#include <errno.h>
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <zlib/zlib.h>

#include "ImfTiledInputFile.h"
#include "ImfTiledMisc.h"
#include "ImfTiledOutputFile.h"
#include "ImfTiledRgbaFile.h"
#include "ImfTileOffsets.h"
#include "ImfTimeCode.h"
#include "ImfTimeCodeAttribute.h"
#include "ImfVecAttribute.h"
#include "ImfVersion.h"
#include "ImfWav.h"
#include "ImfXdr.h"
#include "ImfZipCompressor.h"
#include "b44ExpLogTable.h"
#include "Imf.h"
#include "ImfAcesFile.h"
#include "ImfArray.h"
#include "ImfAttribute.h"
#include "ImfAutoArray.h"
#include "ImfB44Compressor.h"
#include "ImfBoxAttribute.h"
#include "ImfChannelList.h"
#include "ImfChannelListAttribute.h"
#include "ImfCheckedArithmetic.h"
#include "ImfChromaticities.h"
#include "ImfChromaticitiesAttribute.h"
#include "ImfCompression.h"
#include "ImfCompressionAttribute.h"
#include "ImfCompressor.h"
#include "ImfConvert.h"
#include "ImfCRgbaFile.h"
#include "ImfDoubleAttribute.h"
#include "ImfEnvmap.h"
#include "ImfEnvmapAttribute.h"
#include "ImfFloatAttribute.h"
#include "ImfFrameBuffer.h"
#include "ImfFramesPerSecond.h"
#include "ImfHeader.h"
#include "ImfHuf.h"
#include "ImfInputFile.h"
#include "ImfInt64.h"
#include "ImfIntAttribute.h"
#include "ImfIO.h"
#include "ImfKeyCode.h"
#include "ImfKeyCodeAttribute.h"
#include "ImfLineOrder.h"
#include "ImfLineOrderAttribute.h"
#include "ImfLut.h"
#include "ImfMatrixAttribute.h"
#include "ImfMisc.h"
#include "ImfMultiView.h"
#include "ImfName.h"
#include "ImfOpaqueAttribute.h"
#include "ImfOutputFile.h"
#include "ImfPixelType.h"
#include "ImfPizCompressor.h"
#include "ImfPreviewImage.h"
#include "ImfPreviewImageAttribute.h"
#include "ImfPxr24Compressor.h"
#include "ImfRational.h"
#include "ImfRationalAttribute.h"
#include "ImfRgba.h"
#include "ImfRgbaFile.h"
#include "ImfRgbaYca.h"
#include "ImfRleCompressor.h"
#include "ImfScanLineInputFile.h"
#include "ImfStandardAttributes.h"
#include "ImfStdIO.h"
#include "ImfStringAttribute.h"
#include "ImfStringVectorAttribute.h"
#include "ImfTestFile.h"
#include "ImfThreading.h"
#include "ImfTileDescription.h"
#include "ImfTileDescriptionAttribute.h"