 //O volume na unidade Z ‚ eco
 //O N£mero de S‚rie do Volume ‚ 4A91-94E4

 //Pasta de Z:\netnode\app\axis\mysql\strings

#include "bchange.c"
//#include "conf_to_src.c"
//#include "ctype-big5.c"
//#include "ctype-bin.c"
//#include "ctype-cp932.c"
//#include "ctype-czech.c"
//#include "ctype-eucjpms.c"
//#include "ctype-euc_kr.c"
//#include "ctype-extra.c"
//#include "ctype-gb2312.c"
//#include "ctype-gbk.c"
//#include "ctype-latin1.c"
//#include "ctype-mb.c"
//#include "ctype-simple.c"
//#include "ctype-sjis.c"
//#include "ctype-tis620.c"
//#include "ctype-uca.c"
//#include "ctype-ucs2.c"
//#include "ctype-ujis.c"
//#include "ctype-utf8.c"
//#include "ctype-win1250ch.c"
#include "ctype.c"
#include "decimal.c"
//#include "do_ctype.c"
#include "dtoa.c"
//#include "dump_map.c"
#include "int2str.c"
#include "is_prefix.c"
#include "llstr.c"
#include "longlong2str.c"
#include "my_strchr.c"
#include "my_strtoll10.c"
//#include "my_vsnprintf.c"
#include "str2int.c"
#include "strappend.c"
#include "strcend.c"
#include "strcont.c"
#include "strend.c"
#include "strfill.c"
#include "strmake.c"
#include "strmov.c"
#include "strnlen.c"
#include "strnmov.c"
#include "strxmov.c"
#include "strxnmov.c"
#include "str_alloc.c"
//#include "uca-dump.c"
//#include "uctypedump.c"
//#include "utr11-dump.c"
//#include "xml.c"
//2015-02-03  03:57                 0 _strings.c"
//              51 arquivo(s)     16.075.926 bytes
//               0 pasta(s)   28.994.007.040 bytes dispon¡veis
