#include "framework.h"


#include "draw2d_direct2d.cpp"
#include "draw2d_direct2d_bitmap.cpp"
#include "draw2d_direct2d_brush.cpp"
#include "draw2d_direct2d_dib.cpp"
//#include "draw2d_direct2d_directx.cpp"
#include "draw2d_direct2d_factory_exchange.cpp"
#include "draw2d_direct2d_font.cpp"
#include "draw2d_direct2d_graphics.cpp"
#include "draw2d_direct2d_object.cpp"
#include "draw2d_direct2d_palette.cpp"
#include "draw2d_direct2d_path.cpp"
#include "draw2d_direct2d_pen.cpp"
#include "draw2d_direct2d_preview_dc.cpp"
#include "draw2d_direct2d_printer.cpp"
#include "draw2d_direct2d_region.cpp"
#include "draw2d_direct2d_win_tls.cpp"
#include "my_debug.cpp"
