#include "framework.h"


#include "draw2d_opengl.cpp"
#include "draw2d_opengl_bitmap.cpp"
#include "draw2d_opengl_brush.cpp"
#include "draw2d_opengl_dib.cpp"
#include "draw2d_opengl_factory_exchange.cpp"
#include "draw2d_opengl_font.cpp"
#include "draw2d_opengl_graphics.cpp"
#include "draw2d_opengl_object.cpp"
#include "draw2d_opengl_palette.cpp"
#include "draw2d_opengl_path.cpp"
#include "draw2d_opengl_pen.cpp"
#include "draw2d_opengl_preview_dc.cpp"
#include "draw2d_opengl_printer.cpp"
#include "draw2d_opengl_region.cpp"
