#include "framework.h"


#include "draw2d_gdiplus.cpp"
#include "draw2d_gdiplus_bitmap.cpp"
#include "draw2d_gdiplus_brush.cpp"
#include "draw2d_gdiplus_dib.cpp"
#include "draw2d_gdiplus_factory_exchange.cpp"
#include "draw2d_gdiplus_font.cpp"
#include "draw2d_gdiplus_graphics.cpp"
#include "draw2d_gdiplus_object.cpp"
#include "draw2d_gdiplus_palette.cpp"
#include "draw2d_gdiplus_path.cpp"
#include "draw2d_gdiplus_pen.cpp"
#include "draw2d_gdiplus_preview_dc.cpp"
#include "draw2d_gdiplus_printer.cpp"
#include "draw2d_gdiplus_region.cpp"
