#include "framework.h"


#include "draw2d_gl2d.cpp"
#include "draw2d_gl2d_bitmap.cpp"
#include "draw2d_gl2d_brush.cpp"
#include "draw2d_gl2d_dib.cpp"
#include "draw2d_gl2d_factory_exchange.cpp"
#include "draw2d_gl2d_font.cpp"
#include "draw2d_gl2d_graphics.cpp"
#include "draw2d_gl2d_object.cpp"
#include "draw2d_gl2d_palette.cpp"
#include "draw2d_gl2d_path.cpp"
#include "draw2d_gl2d_pen.cpp"
#include "draw2d_gl2d_preview_dc.cpp"
#include "draw2d_gl2d_printer.cpp"
#include "draw2d_gl2d_region.cpp"
