#pragma once

#define ATL_RESID_BASE                  0xD800
#define ATL_STRING_BASE                  ATL_RESID_BASE

#define ATL_IDS_DATETIME_INVALID         (ATL_STRING_BASE + 0)
#define ATL_IDS_DATETIMESPAN_INVALID      (ATL_STRING_BASE + 1)

#define ATL_SERVICE_MANAGER_OPEN_ERROR      (ATL_STRING_BASE + 10)
#define ATL_SERVICE_START_ERROR            (ATL_STRING_BASE + 11)
#define ATL_SERVICE_OPEN_ERROR            (ATL_STRING_BASE + 12)
#define ATL_SERVICE_DELETE_ERROR         (ATL_STRING_BASE + 13)
#define ATL_SERVICE_STOP_ERROR            (ATL_STRING_BASE + 14)
