"Z:\ca2\app\aura\charguess\cpp\pkgInt.h"
"Z:\ca2\app\aura\charguess\cpp\SBCharsetProber.h"
"Z:\ca2\app\aura\charguess\cpp\SBCSGroupProber.h"
"Z:\ca2\app\aura\charguess\cpp\SJISProber.h"
"Z:\ca2\app\aura\charguess\cpp\types.h"
"Z:\ca2\app\aura\charguess\cpp\universal.h"
"Z:\ca2\app\aura\charguess\cpp\UTF8Prober.h"
"Z:\ca2\app\aura\charguess\cpp\big5Prober.h"
"Z:\ca2\app\aura\charguess\cpp\charDistribution.h"
"Z:\ca2\app\aura\charguess\cpp\charsetProber.h"
"Z:\ca2\app\aura\charguess\cpp\codingStateMachine.h"
"Z:\ca2\app\aura\charguess\cpp\config.h"
"Z:\ca2\app\aura\charguess\cpp\EscCharsetProber.h"
"Z:\ca2\app\aura\charguess\cpp\EUCJPProber.h"
"Z:\ca2\app\aura\charguess\cpp\EUCKRProber.h"
"Z:\ca2\app\aura\charguess\cpp\EUCTWProber.h"
"Z:\ca2\app\aura\charguess\cpp\GB2312Prober.h"
"Z:\ca2\app\aura\charguess\cpp\jpCntx.h"
"Z:\ca2\app\aura\charguess\cpp\Latin1Prober.h"
"Z:\ca2\app\aura\charguess\cpp\MBCSGroupProber.h"

#include "big5Prober.h"