#if !defined(AFX_CONTAINEDCONTROLS_H__4F06B44B_71AF_4B3D_9294_1D9D848C1B57__INCLUDED_)
#define AFX_CONTAINEDCONTROLS_H__4F06B44B_71AF_4B3D_9294_1D9D848C1B57__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CContainedControls wrapper class

class CContainedControls : public COleDispatchDriver
{
public:
	CContainedControls() {}		// Calls COleDispatchDriver default constructor
	CContainedControls(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CContainedControls(const CContainedControls& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	LPDISPATCH GetItem(long index);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CONTAINEDCONTROLS_H__4F06B44B_71AF_4B3D_9294_1D9D848C1B57__INCLUDED_)
