 //O volume na unidade Z ‚ eco
 //O N£mero de S‚rie do Volume ‚ 4A91-94E4

 //Pasta de Z:\ca2\app\axis\openssl\crypto\evp

#include "bio_b64.c"
#include "bio_enc.c"
#include "bio_md.c"
#include "bio_ok.c"
#include "c_all.c"
#include "c_allc.c"
#include "c_alld.c"
#include "digest.c"
#include "encode.c"
#include "evp_acnf.c"
#include "evp_cnf.c"
#include "evp_enc.c"
#include "evp_err.c"
#include "evp_fips.c"
#include "evp_key.c"
#include "evp_lib.c"
#include "evp_pbe.c"
#include "evp_pkey.c"
//#include "evp_test.c"
#include "e_aes.c"
#include "e_aes_cbc_hmac_sha1.c"
#include "e_bf.c"
#include "e_camellia.c"
#include "e_cast.c"
#include "e_des.c"
#include "e_des3.c"
//#include "e_dsa.c"
#include "e_idea.c"
#include "e_null.c"
#include "e_old.c"
#include "e_rc2.c"
#include "e_rc4.c"
#include "e_rc4_hmac_md5.c"
#include "e_rc5.c"
#include "e_seed.c"
#include "e_xcbc_d.c"
#include "m_dss.c"
#include "m_dss1.c"
#include "m_ecdsa.c"
#include "m_md2.c"
#include "m_md4.c"
#include "m_md5.c"
#include "m_mdc2.c"
#include "m_null.c"
#include "m_ripemd.c"
#include "m_sha.c"
#include "m_sha1.c"
#include "m_sigver.c"
#include "m_wp.c"
#include "names.c"
#include "openbsd_hw.c"
#include "p5_crpt.c"
#include "p5_crpt2.c"
#include "pmeth_fn.c"
#include "pmeth_gn.c"
#include "pmeth_lib.c"
#include "p_dec.c"
#include "p_enc.c"
#include "p_lib.c"
#include "p_open.c"
#include "p_seal.c"
#include "p_sign.c"
#include "p_verify.c"
//2015-01-03  21:49                 0 _evp.c"
//              64 arquivo(s)        477.765 bytes
//               0 pasta(s)   36.919.476.224 bytes dispon¡veis
